name       : help2man
version    : 1.47.1
release    : 1
source     :
    - http://mirror.aarnet.edu.au/pub/gnu/help2man/help2man-1.47.1.tar.xz : c59b26f60cb06e45b00e729dea721e7a17220e2c17d800eb428271a750382b06
license    : GPL-3.0
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
