name       : help2man
version    : 1.49.3
release    : 13
source     :
    - https://ftp.gnu.org/gnu/help2man/help2man-1.49.3.tar.xz : 4d7e4fdef2eca6afe07a2682151cea78781e0a4e8f9622142d9f70c083a2fd4f
license    : GPL-3.0-or-later
homepage   : https://www.gnu.org/software/help2man/help2man.html
component  : programming.tools
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

# Alternate source, useful for changelogs: https://salsa.debian.org/bod/help2man
