name       : help2man
version    : 1.47.5
release    : 2
source     :
    - https://ftp.gnu.org/gnu/help2man/help2man-1.47.5.tar.xz : 7ca60b2519fdbe97f463fe2df66a6188d18b514bfd44127d985f0234ee2461b1
license    : GPL-3.0
component  : programming.tools
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
