name       : help2man
version    : 1.47.7
release    : 4
source     :
    - https://ftp.gnu.org/gnu/help2man/help2man-1.47.7.tar.xz : 585b8e88ed04bdb426403cf7d9b0c0bb9c7630755b0096c2b018a024b29bec0d
license    : GPL-3.0-or-later
component  : programming.tools
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/%libdir%
