name       : help2man
version    : 1.47.8
release    : 5
source     :
    - https://ftp.gnu.org/gnu/help2man/help2man-1.47.8.tar.xz : 528f6a81ad34cbc76aa7dce5a82f8b3d2078ef065271ab81fda033842018a8dc
license    : GPL-3.0-or-later
component  : programming.tools
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/%libdir%
