name       : help2man
version    : 1.47.6
release    : 3
source     :
    - https://ftp.gnu.org/gnu/help2man/help2man-1.47.6.tar.xz : d91b0295b72a638e4a564f643e4e6d1928779131f628c00f356c13bf336de46f
license    : GPL-3.0
component  : programming.tools
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/%libdir%
