name       : help2man
version    : 1.47.9
release    : 6
source     :
    - https://ftp.gnu.org/gnu/help2man/help2man-1.47.9.tar.xz : df9e8b03937098149c43610efb27980b2d9c799ea7813e9960da4317b75923d2
license    : GPL-3.0-or-later
component  : programming.tools
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/%libdir%
