name       : help2man
version    : 1.47.14
release    : 11
source     :
    - https://ftp.gnu.org/gnu/help2man/help2man-1.47.14.tar.xz : 9152596f244d26d250afed878adfe1d42f82fb87c61c5cba230e00fc34c67383
license    : GPL-3.0-or-later
component  : programming.tools
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
