name       : help2man
version    : 1.47.10
release    : 7
source     :
    - https://mirrors.rit.edu/gnu/help2man/help2man-1.47.10.tar.xz : f371cbfd63f879065422b58fa6b81e21870cd791ef6e11d4528608204aa4dcfb
license    : GPL-3.0-or-later
component  : programming.tools
summary    : help2man
description: |
    help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/%libdir%
